source 'https://rubygems.org'


gem 'capybara', '~> 3.35', '>= 3.35.3'
gem 'capybara-select2'
gem 'chromedriver2-helper'
gem 'faker', '~> 3.2.0'
gem 'nokogiri'
gem 'pry', '~> 0.14', '~> 0.14.1'
gem 'pry-rescue', '~> 1.5'
gem 'pry-stack_explorer', '~> 0.6.0'
gem 'rspec'
gem 'rspec-wait'
gem 'selenium-webdriver', '~> 3.142', '>= 3.142.7'
gem 'waitutil'
