source 'https://rubygems.org'

gem 'allure-rspec', '~> 2.27.0'
gem 'faker', '~> 3.2.0'
gem 'nokogiri'
gem 'pry', '~> 0.14', '~> 0.14.1'
gem 'pry-rescue', '~> 1.5'
gem 'pry-stack_explorer', '~> 0.6.0'
gem 'rspec', '~> 3.13'
gem 'rspec-wait'
gem 'waitutil'
gem 'playwright-ruby-client'
